version: "3.2"
services:
  promtail:
    image: grafana/promtail:2.9.0
    container_name: monstack_promtail
    hostname: monstack_promtail
    volumes:
      - /var/lib/docker/containers:/var/lib/docker/containers:ro #Expose All Container Logs To Promtail
      - /var/run/docker.sock:/var/run/docker.sock #Expose All Container Logs To Promtail
      - /home/peiter/monitoring_system/grafana_stack_confile/promtail-mainconf.yml:/etc/promtail/promtail-mainconf.yml
    restart: unless-stopped
    command: -config.file=/etc/promtail/promtail-mainconf.yml
    networks:
      network_monitoring:
        ipv4_address: 192.168.55.30
  loki:
    image: grafana/loki:2.9.0
    container_name: monstack_loki
    hostname: monstack_loki
    volumes:
      - /home/peiter/monitoring_system/grafana_stack_confile/loki-mainconf.yml:/etc/loki/loki-mainconf.yml
    ports:
      - "3100:3100"
    restart: unless-stopped
    command: -config.file=/etc/loki/loki-mainconf.yml
    networks:
      network_monitoring:
        ipv4_address: 192.168.55.20
networks:
  network_monitoring:
    external: true